name: Request Page Indexing
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Cache Index File
        id: cache-index
        uses: actions/cache@v4
        with:
          path: .cache/
          key: ${{ runner.os }}-cache
      - run: gis kamal.wiki
        env:
          GIS_CLIENT_EMAIL: ${{ secrets.GIS_CLIENT_EMAIL }}
          GIS_PRIVATE_KEY: ${{ secrets.GIS_PRIVATE_KEY }}
